spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FastFood?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update          # <-- Esta línea permite crear o actualizar tablas automáticamente
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
security:
  jwt:
    secret: QulywYuiMZzR90QVVIuIZs9UmBAbDkQQvBmYHlRJtfmJPcfZoa7Hkzv-P9Tvy10f5NvAASEt1NAyS4ZGoWHAEw
    access-token-expiration: 900000  # 15 minutos en milisegundos
    refresh-token-expiration: 900000  # 15 minutos en milisegundos
logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.type.descriptor.sql: TRACE
